### ISSUE TITLE
Update install document to support OSX using Homebrew

### ISSUE THREAD

**Issue by wistephens** [mfisk/filemap#15]
If installing on OSX using Homebrew, use the '--with-poll' option to the python install to avoid the "select.poll() not implemented." error.

$ brew install python --with-poll

**Comment by JensRantil** [comment]
@wistephens Which install document are you refering to?

**Comment by mfisk** [comment]
Fixed in  cb85ddb12bfb8785261f99483357edfcf82c7f40

We now use BSD-style kqueue if there is no select.poll
