### ISSUE TITLE
Support for disabling intermediate results

### ISSUE THREAD

**Issue by JensRantil** [mfisk/filemap#16]
Sometimes, intermediate results might be ginormeous. In this case, it would be useful to disable intermediate caching of stages. Has this been discussed previously?

**Comment by mfisk** [comment]
As of commit efc07c6 (over a year ago) that (no caching) should be the
default for | pipelines.  Use || to get the old, cached behavior.
 However, caching is currently required for shuffles and reduces since,
like Hadoop, that's storage-centric operation.

Cheers,
Mike

**Comment by JensRantil** [comment]
This great news. Thanks, Mike!
